# Generated by Django 6.0.2 on 2026-04-23 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In App')], default='IN_APP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SNOOZED', 'Snoozed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MILESTONE_ACHIEVED', 'Milestone Achieved'), ('GOAL_ACHIEVED', 'Goal Achieved'), ('GOAL_AT_RISK', 'Goal At Risk'), ('GOAL_MISSED', 'Goal Missed'), ('INACTIVITY_REMINDER', 'Inactivity Reminder')], default='NONE', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('achievement_notifs', models.BooleanField(default=True)),
                ('goal_notifs', models.BooleanField(default=True)),
                ('inactivity_reminders', models.BooleanField(default=True)),
                ('inactivity_threshold_days', models.IntegerField(default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
