# Generated by Django 6.0.2 on 2026-04-23 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goal_goals_goal_user_id_7ad9fc_idx_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='idx_notification_user_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notification_user_is_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='idx_notification_type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['goal', 'created_at'], name='idx_notification_goal_created'),
        ),
    ]
