from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from django.contrib.auth.hashers import check_password

from users.business import UserRegistrationService

User = get_user_model()


class RegisterSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True, required=True, validators=[validate_password])
    password2 = serializers.CharField(write_only=True, required=True)

    class Meta:
        model = User
        fields = ("username", "password", "password2", "email", "first_name", "last_name")
        extra_kwargs = {
            "first_name": {"required": False},
            "last_name": {"required": False},
        }

    def validate(self, attrs):
        if attrs["password"] != attrs["password2"]:
            raise serializers.ValidationError({"password": "Password fields didn't match."})
        return attrs

    def create(self, validated_data):
        return UserRegistrationService().register_user(validated_data)


# Backwards-compatible naming alias.
RegisterSerialiser = RegisterSerializer


# Note: Code generated by Gemini (Google AI)
# For Profile Update (Issue # 105)
# Implements password verification before allowing user profile changes.
class ProfileUpdateSerializer(serializers.ModelSerializer):
    current_password = serializers.CharField(write_only=True, required=False)
    new_password = serializers.CharField(
        write_only=True, 
        required=False, 
        validators=[validate_password]
    )

    class Meta:
        model = User
        # Modifiable fields based on your RegisterSerializer fields
        fields = ("username", "email", "first_name", "last_name", "current_password", "new_password")
        extra_kwargs = {
            "username": {"required": False},
            "email": {"required": False},
        }

    def validate(self, attrs):
        # Requirement: Password updates require current password confirmation
        if "new_password" in attrs:
            if "current_password" not in attrs:
                raise serializers.ValidationError({"current_password": "Current password is required to set a new one."})
            
            if not check_password(attrs["current_password"], self.instance.password):
                raise serializers.ValidationError({"current_password": "Current password is incorrect."})
        
        return attrs

    def update(self, instance, validated_data):
        # We handle the actual save logic here or call a Service
        new_password = validated_data.pop("new_password", None)
        validated_data.pop("current_password", None) # Clean up

        for attr, value in validated_data.items():
            setattr(instance, attr, value)

        if new_password:
            instance.set_password(new_password)
        
        instance.save()
        return instance
