# Generated by Django 6.0.2 on 2026-04-04 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activities',
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('strava', 'Strava'), ('mapmyrun', 'MapMyRun'), ('weski', 'We Ski'), ('mywhoosh', 'MyWhoosh')], max_length=50)),
                ('external_user_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connected_accounts',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.connectedaccount'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('account', 'external_id'), name='unique_account_external_id'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'external_user_id'), name='unique_provider_external_user'),
        ),
    ]
