# Generated by Django 6.0.2 on 2026-04-23 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_unique_together_alter_activity_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'date'], name='idx_activity_account_date'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'created_at'], name='idx_activity_account_created'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['date'], name='idx_activity_date'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-date', '-created_at'], name='idx_activity_date_created_desc'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['user'], name='idx_connected_account_user'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['provider'], name='idx_connected_account_provider'),
        ),
    ]
