import pytest
from activities.adapters.iactivity_adapter import IActivityAdapter

# NOTE: This testing class was generated by ChatGPT (OpenAI)

def test_interface_exists():
    assert IActivityAdapter is not None

def test_cannot_instantiate_interface():
    with pytest.raises(TypeError):
        IActivityAdapter()

def test_methods_exist():
    methods = dir(IActivityAdapter)
    assert "parse" in methods
    assert "validate" in methods
    assert "mapToActivity" in methods
    assert "get_provider_name" in methods