from activities.models import Activity
from core.data import BaseRepository


class ActivityRepository(BaseRepository):
    def __init__(self):
        super().__init__(Activity)

    def for_user(self, user):
        return self.model.objects.filter(user=user).order_by("-date", "-created_at")

    def apply_filters(self, queryset, params):
        provider = params.get("provider")
        date_from = params.get("date_from")
        date_to = params.get("date_to")

        if provider:
            queryset = queryset.filter(provider=provider)
        if date_from:
            queryset = queryset.filter(date__gte=date_from)
        if date_to:
            queryset = queryset.filter(date__lte=date_to)

        return queryset

    def has_duplicate_external_activity(self, provider, external_id, exclude_pk=None):
        queryset = self.model.objects.filter(provider=provider, external_id=external_id)
        if exclude_pk is not None:
            queryset = queryset.exclude(pk=exclude_pk)
        return queryset.exists()

    def delete(self, instance):
        """
        Permanently removes the activity record from the database.
        """
        instance.delete()
    
    def get_by_id(self, activity_id):
        try:
            return self.model.objects.get(pk=activity_id)
        except self.model.DoesNotExist:
            return None

    # Note: Code generated by Gemini (Google AI)
    # Issue 106: Feature: Activity Modification
    def update(self, instance, validated_data):
        """
        Updates the activity instance with validated data and persists to DB.
        """
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        
        instance.save()
        return instance
