import pytest
from activities.data.adapters.activity_adapter_base import ActivityAdapter

import json

# DISCLOSURE: This test file was generated by ChatGPT (OpenAI) and edited to fit the codebase more accurately.

TEST_SCHEMA = {
    "type": "object",
    "properties": {
        "external_id": {"type": "string"},
        "name": {"type": "string"},
        "sport_type": {"type": "string"},
        "activity_type": {"type": "string"},
        "distance": {"type": "number"},
        "moving_time": {"type": "integer"},
        "elapsed_time": {"type": "integer"},
        "total_elevation_gain": {"type": "number"},
        "start_date": {"type": "string", "format": "date-time"},
        "start_date_local": {"type": "string", "format": "date-time"},
        "timezone": {"type": "string"},
        "average_speed": {"type": "number"},
        "max_speed": {"type": "number"},
        "raw_data": {"type": "object"},
    },
    "required": [
        "external_id",
        "name",
        "distance",
        "moving_time",
        "elapsed_time",
        "total_elevation_gain",
        "raw_data",
    ],
}

VALID_ACTIVITY = {
        "external_id": "abc123",
        "name": "Morning Run",
        "sport_type": "Run",
        "activity_type": "Workout",
        "distance": 5000.0,
        "moving_time": 1500,
        "elapsed_time": 1600,
        "total_elevation_gain": 50.0,
        "start_date": "2024-01-01T10:00:00Z",
        "start_date_local": "2024-01-01T05:00:00-05:00",
        "timezone": "America/New_York",
        "average_speed": 3.3,
        "max_speed": 5.0,
        "raw_data": {"foo": "bar"},
    }

@pytest.fixture
def test_schema() -> dict:
    schema = TEST_SCHEMA.copy()
    schema['properties'] = schema['properties'].copy()
    return schema

@pytest.fixture
def base_adapter(test_schema) -> ActivityAdapter:
    return ActivityAdapter(None, test_schema)

@pytest.fixture
def valid_activity(test_schema, base_adapter) -> str:
    return VALID_ACTIVITY.copy()

class TestAdapterValidate:

    def _validate_dict(adapter, activity):
        valid, _ = adapter.validate(json.dumps(activity))
        return valid

    # Valid cases
    def test_valid_activity_passes(test_schema, base_adapter, valid_activity):
        assert TestAdapterValidate._validate_dict(base_adapter, valid_activity)


    def test_optional_fields_missing(test_schema, base_adapter, valid_activity):
        data = valid_activity
        del data["average_speed"]
        del data["max_speed"]
        assert TestAdapterValidate._validate_dict(base_adapter, data)


    # REQUIRED FIELD TESTS

    @pytest.mark.parametrize("field", TEST_SCHEMA["required"])
    def test_missing_required_fields_fail(self, field, test_schema, base_adapter, valid_activity):
        data = valid_activity
        del data[field]
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    # TYPE VALIDATION

    @pytest.mark.parametrize(
        "field, bad_value",
        [
            ("external_id", 123),
            ("name", 999),
            ("distance", "far"),
            ("moving_time", 12.5),
            ("elapsed_time", "long"),
            ("total_elevation_gain", "high"),
            ("raw_data", "not a dict"),
        ],
    )
    def test_wrong_types_fail(self, field, bad_value, test_schema, base_adapter, valid_activity):
        data = valid_activity
        data[field] = bad_value
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    # DATETIME VALIDATION

    @pytest.mark.parametrize(
    "field,bad_value",
    [
        ("start_date", "not-a-date"),
        ("start_date_local", "2024/01/01"),
        ("start_date", "2024-13-01T00:00:00Z"),  # invalid month
    ])
    def test_invalid_datetime_format(self, field, bad_value, test_schema, base_adapter, valid_activity):
        data = valid_activity
        data[field] = bad_value
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    # EDGE CASES

    def test_zero_values(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["distance"] = 0
        data["moving_time"] = 0
        assert TestAdapterValidate._validate_dict(base_adapter, data)


    def test_empty_strings(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["name"] = ""
        assert TestAdapterValidate._validate_dict(base_adapter, data)  # allowed unless you restrict


    def test_extra_fields_allowed(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["extra_field"] = "extra"
        assert TestAdapterValidate._validate_dict(base_adapter, data)


    # SCHEMA VARIATION TESTS

    def test_schema_with_additional_required_field(test_schema, base_adapter, valid_activity):
        schema = base_adapter.activity_schema
        schema["required"] = schema["required"] + ["sport_type"]

        data = valid_activity
        assert TestAdapterValidate._validate_dict(base_adapter, data)

        del data["sport_type"]
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    def test_schema_with_stricter_raw_data(test_schema, base_adapter, valid_activity):
        schema = base_adapter.activity_schema
        schema["properties"]["raw_data"] = {
            "type": "object",
            "properties": {
                "foo": {"type": "string"}
            },
            "required": ["foo"]
        }

        data = valid_activity
        assert TestAdapterValidate._validate_dict(base_adapter, data)

        data["raw_data"] = {}
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    # NULL / NONE HANDLING

    def test_none_in_required_field(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["name"] = None
        assert not TestAdapterValidate._validate_dict(base_adapter, data)


    # STRESS / ROBUSTNESS

    def test_large_numbers(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["distance"] = 1e12
        assert TestAdapterValidate._validate_dict(base_adapter, data)


    def test_nested_raw_data(test_schema, base_adapter, valid_activity):
        data = valid_activity
        data["raw_data"] = {"nested": {"deep": {"value": 1}}}
        assert TestAdapterValidate._validate_dict(base_adapter, data)

class TestAdapterHooks:

    def test_register_hooks_appends_hooks(self, base_adapter):
        calls = []

        def hook1(): calls.append("start1")
        def hook2(): calls.append("success1")
        def hook3(): calls.append("fail1")

        base_adapter.register_hooks(([hook1], [hook2], [hook3]))

        # Trigger manually
        base_adapter._start_parse()
        base_adapter._succeed_parse()
        base_adapter._fail_parse()

        assert calls == ["start1", "success1", "fail1"]


    def test_register_hooks_multiple_calls_accumulate(self, base_adapter):
        calls = []

        def hook1(): calls.append("a")
        def hook2(): calls.append("b")

        base_adapter.register_hooks(([hook1], [], []))
        base_adapter.register_hooks(([hook2], [], []))

        base_adapter._start_parse()

        assert calls == ["a", "b"]


    def test_hooks_run_in_order(self, base_adapter):
        calls = []

        def hook1(): calls.append(1)
        def hook2(): calls.append(2)
        def hook3(): calls.append(3)

        base_adapter.register_hooks(([hook1, hook2, hook3], [], []))
        base_adapter._start_parse()

        assert calls == [1, 2, 3]


    def test_empty_hooks_do_nothing(self, base_adapter):
        # Should not raise
        base_adapter.register_hooks(([], [], []))
        base_adapter._start_parse()
        base_adapter._succeed_parse()
        base_adapter._fail_parse()


    def test_hook_exception_propagates(self, base_adapter):
        def bad_hook():
            raise RuntimeError("hook failed")

        base_adapter.register_hooks(([bad_hook], [], []))

        with pytest.raises(RuntimeError):
            base_adapter._start_parse()


class TestAdapterParse:

    def test_parse_returns_activity_object(self, base_adapter, valid_activity):
        result = base_adapter.parse(json.dumps(valid_activity))

        # We don't import Activity class, so check attributes instead
        assert result.external_id == valid_activity["external_id"]
        assert result.name == valid_activity["name"]


    def test_parse_sets_all_attributes(self, base_adapter, valid_activity):
        result = base_adapter.parse(json.dumps(valid_activity))

        for key, value in valid_activity.items():
            assert getattr(result, key) == value


    def test_parse_invalid_input_raises(self, base_adapter, valid_activity):
        data = valid_activity
        del data["external_id"]

        with pytest.raises(ValueError, match="Input data was not valid"):
            base_adapter.parse(json.dumps(data))


    def test_parse_calls_validate(self, base_adapter, valid_activity, monkeypatch):
        called = {"validate": False}

        def fake_validate(_):
            called["validate"] = True
            return True, None

        monkeypatch.setattr(base_adapter, "validate", fake_validate)

        base_adapter.parse(json.dumps(valid_activity))
        assert called["validate"]


    def test_parse_does_not_continue_on_invalid(self, base_adapter, valid_activity, monkeypatch):
        def fake_validate(_):
            return False, "bad"

        monkeypatch.setattr(base_adapter, "validate", fake_validate)

        with pytest.raises(ValueError):
            base_adapter.parse(json.dumps(valid_activity))


    def test_parse_uses_conversion_method(self, base_adapter, valid_activity, monkeypatch):
        called = {"convert": False}

        def fake_convert(_):
            called["convert"] = True
            return valid_activity

        monkeypatch.setattr(base_adapter, "_convert_raw_input_data_to_dict", fake_convert)

        base_adapter.parse(json.dumps(valid_activity))
        assert called["convert"]


    def test_parse_overwrites_existing_attributes(self, base_adapter, valid_activity, monkeypatch):
        # Ensure setattr is actually used dynamically
        modified = valid_activity.copy()
        modified["name"] = "Modified Name"

        monkeypatch.setattr(
            base_adapter,
            "_convert_raw_input_data_to_dict",
            lambda _: modified
        )

        result = base_adapter.parse(json.dumps(valid_activity))
        assert result.name == "Modified Name"


    def test_parse_handles_empty_object(self, base_adapter, monkeypatch):
        # Simulate valid but empty dict
        monkeypatch.setattr(base_adapter, "validate", lambda _: (True, None))
        monkeypatch.setattr(base_adapter, "_convert_raw_input_data_to_dict", lambda _: {})

        result = base_adapter.parse("{}")

        # Should not crash, just return empty Activity
        assert result is not None


    def test_parse_with_hooks_integration(self, base_adapter, valid_activity):
        calls = []

        def start(): calls.append("start")
        def success(): calls.append("success")

        base_adapter.register_hooks(([start], [success], []))

        base_adapter.parse(json.dumps(valid_activity))

        assert calls == ["start", "success"]

    def test_parse_invalid_triggers_failure_hook(self, base_adapter, valid_activity):
        calls = []

        def start(): calls.append("start")
        def success(): calls.append("success")
        def fail(): calls.append("fail")

        base_adapter.register_hooks(([start], [success], [fail]))

        # Make data invalid
        invalid = valid_activity
        del invalid["external_id"]

        with pytest.raises(ValueError):
            base_adapter.parse(json.dumps(invalid))

        assert calls == ["start", "fail"]