from django.contrib.auth import get_user_model
from rest_framework import generics
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from users.serializers import RegisterSerializer, ProfileUpdateSerializer, LogoutSerializer

User = get_user_model()

class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer

# Note: Code generated by Gemini (Google AI)
# For Profile Update (Issue #105)
class ProfileUpdateView(generics.RetrieveUpdateAPIView):
    """
    GET: Retrieve the authenticated user's profile
    PATCH/PUT: Update the authenticated user's profile
    """
    serializer_class = ProfileUpdateSerializer
    permission_classes = (IsAuthenticated,)

    def get_object(self):
        # Requirement: Users can only update their own profile.
        # This returns the user associated with the JWT token.
        return self.request.user

class LogoutView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        serializer = LogoutSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"message": "Logout successful"}, status=status.HTTP_200_OK)