# Generated by Django 6.0.2 on 2026-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="progress_state",
            field=models.CharField(
                choices=[
                    ("ON_TRACK", "On Track"),
                    ("ACHIEVED", "Achieved"),
                    ("AT_RISK", "At Risk"),
                    ("MISSED", "Missed"),
                ],
                default="ON_TRACK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="progress_state_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
