# Generated by Django 6.0.2 on 2026-04-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_unique_together_alter_activity_table_and_more'),
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='activities.activity')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='goals.goal')),
            ],
            options={
                'db_table': 'progress_log',
                'constraints': [models.UniqueConstraint(fields=('goal', 'activity'), name='unique_goal_activity')],
            },
        ),
    ]
