# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_goal_progress_state"),
        ("goals", "0003_progresslog"),
    ]

    operations = [
    ]
