# Generated by Django 6.0.2 on 2026-04-22 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_unique_together_alter_activity_table_and_more'),
        ('goals', '0004_merge_0003_goal_progress_state_0003_progresslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'goal_type'], name='goals_goal_user_id_136a72_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'progress_state'], name='goals_goal_user_id_cdfbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['end_date'], name='goals_goal_end_dat_7bb13c_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['updated_at'], name='goals_goal_updated_7ac619_idx'),
        ),
    ]
