# Generated by Django 6.0.2 on 2026-04-05 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('strava', 'Strava'), ('mapmyrun', 'MapMyRun'), ('weski', 'We Ski'), ('mywhoosh', 'MyWhoosh')], max_length=20)),
                ('consent_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='data_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_integration_data_consent',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
