# Generated by Django 6.0.2 on 2026-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMyRunActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activity_key', models.CharField(blank=True, max_length=255, null=True)),
                ('workout_date', models.DateField()),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_burned_kcal', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField()),
                ('workout_time_seconds', models.IntegerField()),
                ('avg_pace_min_per_km', models.FloatField(blank=True, null=True)),
                ('max_pace_min_per_km', models.FloatField(blank=True, null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('max_speed_kmh', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-workout_date'],
            },
        ),
    ]
