# Generated by Django 6.0.2 on 2026-04-08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('strava', 'Strava'), ('mapmyrun', 'MapMyRun'), ('weski', 'We Ski'), ('mywhoosh', 'MyWhoosh')], max_length=20)),
                ('consent_granted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='data_consent_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_integration_data_consent_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
