# Generated by Django 6.0.2 on 2026-04-08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0002_dataconsenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_service', models.CharField(max_length=128)),
                ('requested_user_id', models.IntegerField()),
                ('provider_id', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=128)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny'), ('INFO', 'Info')], max_length=8)),
                ('reason', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('VERIFY', 'Verify'), ('UPDATE', 'Update'), ('HISTORY', 'History')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'privacy_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='privacy_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_status',
                'unique_together': {('user', 'provider_id', 'scope')},
            },
        ),
    ]
