import pytest
import tempfile
import os
from pathlib import Path
from unittest.mock import patch, MagicMock
from data_integration.mapmyrun import validate_upload, upload_to_blob


# Tests generated by COPILOT
class TestValidateUpload:
    """Test suite for validate_upload function"""

    def test_validate_upload_missing_file(self):
        """Test that missing files are rejected"""
        is_valid, error = validate_upload("/nonexistent/file.xlsx")
        assert not is_valid
        assert "not found" in error.lower()

    def test_validate_upload_invalid_extension_txt(self):
        """Test that .txt files are rejected"""
        with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as tmp:
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert not is_valid
            assert "Unsupported file type" in error
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_invalid_extension_pdf(self):
        """Test that .pdf files are rejected"""
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert not is_valid
            assert "Unsupported file type" in error
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_empty_file(self):
        """Test that empty files are rejected"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert not is_valid
            assert "empty" in error.lower()
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_valid_xlsx_file(self):
        """Test that valid .xlsx files pass validation"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"PK\x03\x04")  # Mimics xlsx header
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert is_valid
            assert error is None
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_valid_xls_file(self):
        """Test that valid .xls files pass validation"""
        with tempfile.NamedTemporaryFile(suffix=".xls", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert is_valid
            assert error is None
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_file_exceeds_size_limit(self):
        """Test that files exceeding 10MB are rejected"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            # Create a file larger than 10MB
            tmp.write(b"x" * (11 * 1024 * 1024))
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert not is_valid
            assert "exceeds the 10 MB limit" in error
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_file_exactly_10mb(self):
        """Test that files exactly at 10MB limit are accepted"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"x" * (10 * 1024 * 1024))
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert is_valid
            assert error is None
        finally:
            os.unlink(tmp_path)

    def test_validate_upload_case_insensitive_extension(self):
        """Test that file extensions are case-insensitive"""
        with tempfile.NamedTemporaryFile(suffix=".XLSX", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name
        try:
            is_valid, error = validate_upload(tmp_path)
            assert is_valid
            assert error is None
        finally:
            os.unlink(tmp_path)


class TestUploadToBlob:
    """Test suite for upload_to_blob function"""

    @patch('data_integration.mapmyrun.BlobClient')
    @patch.dict(os.environ, {"AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=test;AccountKey=test"})
    def test_upload_to_blob_success(self, mock_blob_client):
        """Test successful upload to Azure Blob Storage"""
        mock_instance = MagicMock()
        mock_instance.url = "https://test.blob.core.windows.net/habit-tracker/test-file.xlsx"
        mock_blob_client.from_connection_string.return_value = mock_instance

        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name

        try:
            success, result = upload_to_blob(tmp_path)
            assert success
            assert "blob.core.windows.net" in result
            mock_instance.upload_blob.assert_called_once()
        finally:
            os.unlink(tmp_path)

    @patch.dict(os.environ, {}, clear=True)
    def test_upload_to_blob_no_connection_string(self):
        """Test that upload fails without Azure connection string"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name

        try:
            success, result = upload_to_blob(tmp_path)
            assert not success
            assert "AZURE_STORAGE_CONNECTION_STRING is not set" in result
        finally:
            os.unlink(tmp_path)

    @patch.dict(os.environ, {"AZURE_STORAGE_CONNECTION_STRING": ""})
    def test_upload_to_blob_empty_connection_string(self):
        """Test that upload fails with empty connection string"""
        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name

        try:
            success, result = upload_to_blob(tmp_path)
            assert not success
            assert "AZURE_STORAGE_CONNECTION_STRING is not set" in result
        finally:
            os.unlink(tmp_path)

    def test_upload_to_blob_invalid_file(self):
        """Test that upload fails for invalid files"""
        success, result = upload_to_blob("/nonexistent/file.xlsx")
        assert not success
        assert "not found" in result.lower()

    @patch('data_integration.mapmyrun.BlobClient')
    @patch.dict(os.environ, {"AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=test;AccountKey=test"})
    def test_upload_to_blob_azure_exception(self, mock_blob_client):
        """Test that Azure exceptions are handled gracefully"""
        mock_blob_client.from_connection_string.side_effect = Exception("Connection failed")

        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name

        try:
            success, result = upload_to_blob(tmp_path)
            assert not success
            assert "Upload failed" in result
        finally:
            os.unlink(tmp_path)

    @patch('data_integration.mapmyrun.BlobClient')
    @patch.dict(os.environ, {"AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=test;AccountKey=test"})
    def test_upload_to_blob_generates_unique_name(self, mock_blob_client):
        """Test that unique blob names are generated"""
        mock_instance = MagicMock()
        mock_instance.url = "https://test.blob.core.windows.net/habit-tracker/unique-file.xlsx"
        mock_blob_client.from_connection_string.return_value = mock_instance

        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
            tmp.write(b"test data")
            tmp_path = tmp.name

        try:
            upload_to_blob(tmp_path)
            # Get the blob_name argument passed to BlobClient constructor
            call_kwargs = mock_blob_client.from_connection_string.call_args[1]
            blob_name = call_kwargs['blob_name']
            # Should contain uuid format (36 chars) + extension
            assert blob_name.endswith('.xlsx')
            assert len(blob_name) == 41  # 36 char UUID + 5 char extension
        finally:
            os.unlink(tmp_path)
#End of generated tests