# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend', max_length=100)),
                ('badge_type', models.CharField(choices=[('single', 'Single Activity'), ('cumulative', 'Cumulative'), ('streak', 'Streak'), ('frequency', 'Frequency')], max_length=20)),
                ('activity_type', models.CharField(blank=True, help_text='Activity type this badge applies to, blank = any activity', max_length=100)),
                ('threshold', models.DecimalField(decimal_places=2, help_text='The value the user must reach (km, minutes, count, etc.)', max_digits=10)),
                ('metric', models.CharField(default='distance', help_text='What is being measured: distance, duration, calories, count', max_length=50)),
                ('points', models.PositiveIntegerField(default=0, help_text='Coins/points awarded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('metric', models.CharField(choices=[('total_distance', 'Total Distance'), ('total_duration', 'Total Duration'), ('total_calories', 'Total Calories'), ('total_activities', 'Total Activities')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_type', models.CharField(blank=True, help_text='Blank = all activity types', max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['metric', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reached_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reached_at'],
                'unique_together': {('user', 'milestone')},
            },
        ),
    ]
