# Generated by Django 6.0.2 on 2026-04-22 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'threshold'], name='gamificatio_badge_t_ce337d_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['activity_type', 'metric'], name='gamificatio_activit_d98666_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['metric', 'threshold'], name='gamificatio_metric_fabb21_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['activity_type', 'metric'], name='gamificatio_activit_2f5d86_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_activity_date'], name='gamificatio_last_ac_c1266c_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', '-earned_at'], name='gamificatio_user_id_44649b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge', '-earned_at'], name='gamificatio_badge_i_a9d59a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermilestone',
            index=models.Index(fields=['user', '-reached_at'], name='gamificatio_user_id_8b7c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='usermilestone',
            index=models.Index(fields=['milestone', '-reached_at'], name='gamificatio_milesto_618baf_idx'),
        ),
    ]
