# Generated by Django 6.0.2 on 2026-04-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_oauth_p_22ab0d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_provider_id',
        ),
    ]
