name: Block PR After Contribution Deadline

on:
  pull_request:
    branches: ["main"]

jobs:
  block:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write

    steps:
      - uses: yykamei/block-merge-based-on-time@main
        id: block
        with:
          timezone: "UTC-4"
          after: 00:00
          before: 23:59
          base-branches: "(default)"
          prohibited-days-dates: "2026-03-29, 2026-04-08, 2026-04-15" #can modify the dates 

      - run: echo pr-blocked=${{ steps.block.outputs.pr-blocked }}
        if: github.event_name == 'pull_request'